export enum ResponseMessage {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  CREATED = 'CREATED',
  OK = 'OK',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
